name: Conda Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set pytorch-3dunet version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print pytorch-3dunet version
      run: echo $RELEASE_VERSION
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: ""
        channels: local,conda-forge,defaults
        channel-priority: false
    - shell: bash -l {0}
      run: conda info --envs
    - name: Build pytorch-3dunet using Boa
      shell: bash -l {0}
      run: |
        conda install --yes -c conda-forge mamba
        mamba install -q boa
        mamba mambabuild -c pytorch -c nvidia -c conda-forge conda-recipe
    - name: Create pytorch3dunet env
      run: |
        mamba create -n pytorch3dunet -c pytorch -c nvidia -c conda-forge pytorch-3dunet pytest
    - name: Run pytest
      shell: bash -l {0}
      run: |
        conda activate pytorch3dunet
        pytest
        conda deactivate
    - name: Deploy on conda
      if: ${{ startsWith( github.ref, 'refs/tags/') && success() }}
      env:
        ANACONDA_SECRET: ${{ secrets.ANACONDA_TOKEN }}
      shell: bash -l {0}
      run: |
        mamba install -q anaconda-client
        anaconda -t $ANACONDA_SECRET upload $CONDA/conda-bld/**/pytorch-3dunet-*.tar.bz2
